config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      match '*any' => 'api/v1/application#options', :via => [:options]
      resources :connections, only: [:index, :show]
      resources :stations, only: [:index]
    end
  end

  resources :connections

  root 'connections#index'

end

app/models/action/crawl/intercity.rb
module Action
  module Crawl
    class Intercity

		def initialize (start_date, end_date, connection)
			@start_date = start_date
			@end_date = end_date
			@new_courses = []
			@connection = connection
		end

		def execute
			make_site_offline
			remove_existing_courses
			load_new_courses
			save_new_courses
			make_site_online
		end

		def remove_existing_courses
			(@start_date..@end_date).each do |date|
				time_range = @start_date.beginning_of_day..@end_date.end_of_day
				Course.where(departure_time: time_range, connection: @connection).destroy_all
			end
		end

		def load_new_courses
			(@start_date..@end_date).each do |date|

				results = false
				while results == false
					crowler = ::Crowler.new(date, @connection)
					results = crowler.perform_crawl
					puts "repeating day crawl..." unless results
				end

				@new_courses.concat results
			end
		end

		def save_new_courses
			@new_courses.each do |nc|
				nc.save!
			end
		end

		def make_site_offline
			#TODO
		end

		def make_site_online
			#TODO
		end
  	end
  end
end

app/models/connection.rb
class Connection < ActiveRecord::Base
	belongs_to :station
	belongs_to :connected_station, :class_name => "Station"
	has_many :courses	, dependent: :destroy

  alias_attribute :start, :station
  alias_attribute :end, :connected_station

	def self.find_by_station_names(starting, ending)
		start_station = Station.find_by_name(starting)
		end_station = Station.find_by_name(ending)
		Connection.where(station: start_station, connected_station: end_station).first
	end

	def start_station_name
		station.name
	end

	def end_station_name
		connected_station.name
	end

	def name
		"#{start_station_name} -> #{end_station_name}"
	end
end

app/models/course.rb
class Course < ActiveRecord::Base
	belongs_to :connection

	def departure_dayname
		case departure_time.wday
		when 1
			"poniedziałek"
		when 2
			"wtorek"
		when 3
			"środa"
		when 4
			"czwartek"
		when 5
			"piątek"
		when 6
			"sobota"
		when 0
			"niedziela"
		end
	end
end

app/models/station.rb
class Station < ActiveRecord::Base
	has_many :connections, dependent: :destroy
	has_many :connected_stations, :through => :connections
end

app/controllers/api/v1/application_controller.rb
class API::V1::ApplicationController < ActionController::API
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/api/v1/connections_controller.rb
class API::V1::ConnectionsController < API::V1::ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  before_action :set_connection, only: [:show]
  before_filter :add_allow_credentials_headers

  def index
    render json: Connection.includes(:station).all.to_json(only: [:id],include: {station: {only: :name}, connected_station: {only: :name}})
  end

  def show
    render json: @connection.courses.all.to_json(only: [:id, :price, :departure_time, :arrival_time])
  end

  def options
    head :status => 200, :'Access-Control-Allow-Headers' => 'accept, content-type'
  end

  private

  def set_connection
    @connection = Connection.find(params[:id])
  end

  def add_allow_credentials_headers
    # https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#section_5
    #
    # Because we want our front-end to send cookies to allow the API to be authenticated
    # (using 'withCredentials' in the XMLHttpRequest), we need to add some headers so
    # the browser will not reject the response
    response.headers['Access-Control-Allow-Origin'] = request.headers['Origin'] || '*'
    response.headers['Access-Control-Allow-Credentials'] = 'true'
  end
end

app/controllers/api/v1/stations_controller.rb
class API::V1::StationsController < API::V1::ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  def index
    render json: Station.all.to_json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  before_action :set_connection, only: [:show]

  def index
    if params[:connection].present?
      redirect_to connection_path(params[:connection])
      return
    end
    @connections = Connection.all
  end

  def show
    @courses = Course.where(connection: @connection).order(:departure_time).paginate(page: params[:page], :per_page => 20)
    @cheapest_price = Course.where(connection: @connection).minimum(:price)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_connection
      @connection = Connection.find(params[:id])
    end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:name, :connection_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/connection_helper.rb
module ConnectionHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/connections/show.html.erb
    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2><%= @connection.name %></h2>
                    <h3>Najniższa cena na tej linii to <b><%= @cheapest_price.to_s %> zł</b></h3>
                </div>
            </div>
        </div>
    </section>
    <aside class="bg-dark" style="padding-top:20px">
        <div class="container">
            <div class='will_paginate_courses'>
                <%= will_paginate @courses, renderer: BootstrapPagination::Rails %>
            </div>
			<table class="table table-hover courses">
			    <thead>
			      <tr>
			        <th width="33%">Odjazd</th>
			        <th width="33%">Przyjazd</th>
			        <th width="34%">Cena</th>
			      </tr>
			    </thead>
			    <tbody>
                    <!-- #TODO refactor this -->
			    <% @courses.each_with_index do |c, i|%>
                <% if (i == 0) || (@courses[i-1].departure_time.to_date != c.departure_time.to_date) %>
                    <tr>
                        <td colspan="3" class="table-day">
                            <div class="day-name">
                                <%= c.departure_dayname.upcase %> <%= c.departure_time.to_date %>
                            </div>
                        </td>
                    </tr>
                <% end %>
			      <tr class=" <%= (c.departure_time.saturday?||c.departure_time.sunday?)? 'weekend' : '' %> ">
			        <td>
                        <span class="table-date"><%= c.departure_time.to_date %></span><br>
                        <span class="table-time"><%= c.departure_time.strftime("%H:%M") %></span>
                    </td>
                    <td>
                        <span class="table-date"><%= c.arrival_time.to_date %></span><br>
                        <span class="table-time"><%= c.arrival_time.strftime("%H:%M") %></span>
                    </td>
			        <td>
                        <span class="table-price">
                            <% if c.price==@cheapest_price %>
                                <span style="color:#EF8D00"><b><%= c.price %>zł </b></span>  <span class="label label-cheapest"> Najtaniej!</span>
                            <% elsif c.price.present? %>
                                <%= c.price %>zł
                            <% else %>
                                brak
                            <% end %>
                        </span>
                    </td>
			      </tr>
			     <% end %>
			    </tbody>
			  </table>
                <div class='will_paginate_courses'>
                    <%= will_paginate @courses, renderer: BootstrapPagination::Rails %>
                </div>
        </div>
    </aside>
    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Używasz wersji beta!</h2>
                    <hr class="primary">
                    <p>Aplikacja może zawierać błędy i jest wciąż modyfikowana!</p>
                    <p><a href="mailto:kocasp@gmail.com">kocasp@gmail.com</a></p>
                </div>
            </div>
        </div>
    </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsFox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand page-scroll" href="/"><%= image_tag 'tail.png' %>RailsFox <small>beta</small></a>
        </div>
    </div>
</nav>

<%= yield %>

</body>
</html>

app/views/stations/_form.html.erb
<%= form_for(@station) do |f| %>
  <% if @station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% @station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :connection_id %><br>
    <%= f.number_field :connection_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing Station</h1>

<%= render 'form' %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Connection</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td><%= station.name %></td>
        <td><%= station.connection_id %></td>
        <td><%= link_to 'Show', station %></td>
        <td><%= link_to 'Edit', edit_station_path(station) %></td>
        <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Station', new_station_path %>

app/views/stations/new.html.erb
<h1>New Station</h1>

<%= render 'form' %>

<%= link_to 'Back', stations_path %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @station.name %>
</p>

<p>
  <strong>Connection:</strong>
  <%= @station.connection_id %>
</p>

<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>